version: '3'
 
services:
  api:
    build: .
    volumes:
      - '.:/app'
      - '/app/vendor'
    restart: "always"
    ports:
    - "8000:8000"
    environment:
      - VIRTUAL_HOST=api.example.com
      - LETSENCRYPT_HOST=api.example.com
      - VIRTUAL_PORT=8000
    network_mode: bridge
