version: '3.3'

services:
  api:
    build: .
    volumes:
      - '.:/app'
      - '/app/vendor'
      - './kernel/Infrastructure/mysql/var/lib/mysql:/var/lib/mysql'
      - './kernel/Infrastructure/mysql/etc/mysql/conf.d:/etc/mysql/conf.d'
    restart: "always"
    ports:
    - "8000:8000"
    environment:
        # host only for reverse proxy run:
        # https://github.com/0zuna/Docker/blob/main/proxy/docker-compose.yml
        # - VIRTUAL_HOST=host.example.com
        # - LETSENCRYPT_HOST=host.example.com
        # - VIRTUAL_PORT=8000
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=app-api
      - LARAVEL_SEEDING=no #'yes' only first time and not found /kernel/Infrastructure/mysql
    network_mode: bridge
